#!/bin/bash

PEWS_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"

#create directories that can't be included in .tar.gz
mkdir $PEWS_HOME/log
mkdir $PEWS_HOME/db


LIB=${PEWS_HOME}/lib
PLUGIN=${PEWS_HOME}/plugin
PEWS_HOME_PROP=-Dch.zhaw.iwi.cis.pews.pewsHome=${PEWS_HOME}
LOGGING_PROP=-Djava.util.logging.config.file=${PEWS_HOME}/conf/logging.properties

for arg in "$@" ; do
  if [ "$arg" = "-debug" ] ; then
    DEBUG="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=y"
  fi
done

cd ${PEWS_HOME}

for jar in $LIB/* $PLUGIN/*
do
	CLASSPATH=${CLASSPATH}:$jar
done

java -classpath ${CLASSPATH} ${DEBUG} ${PEWS_HOME_PROP} ${LOGGING_PROP} ch.zhaw.iwi.cis.pews.framework.ZhawEngine $*
